name: Publish Nuget package
on:
  release:
    types: [published]
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Create the package
        run: dotnet pack -c Release CollectionExtensions
      - name: Publish the package to nuget.orkg
        run: |
          tag=${{ github.ref_name }}
          version="${tag:1}"
          dotnet nuget push CollectionExtensions/bin/Release/*$version.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
